env:
  global:
   - secure: "FmxuRiy1JnO2wBdU2h4j6XzEg+kS5j9m8b7DuFdCPWkFQT41PYmSnuMTGQHlPnXra/USD2QK8kv7FE1+Rfn59CoHVTUEXVjKxe8mz3le/TwYS9FMZx+uAqCoSd0mExp4sZ+Amr8FDISgViDtEKIBS+QPTcDRF/x6fvodyF3WJxs="
addons:
  coverity_scan:
    project:
      name: "brunojensen/bea.androidtools"
      description: "Build submitted via Travis CI"
    notification_email: ordead6@gmail.com
    build_command_prepend: "mvn clean"
    build_command:   "mvn -DskipTests=true compile"
    branch_pattern: coverity_scan
language: java
jdk:
  - openjdk6
before_install:
  # download the latest android sdk and unzip
  - wget http://dl.google.com/android/android-sdk_r18-linux.tgz
  - tar -zxf android-sdk_r18-linux.tgz
  - export ANDROID_HOME=`pwd`/android-sdk-linux
  - export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools
  # only update the sdk for the tools and platform-tools (1,2) and whatever api level
  # you are building for android (run "android list sdk" to get the full list.  9 = 2.3.3 or API level 10
  - android update sdk --filter 1,2,9 --no-ui --force
install:
  - mvn clean install
